version: "3.5"

services:
  influxdb:
    image: influxdb:1.8.4
    container_name: influxdb
    volumes:
      - ./influxdb/influx_data:/var/lib/influxdb
    ports:
      - "8086:8086"
    networks: 
      - monitoring
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    user: $UID
    volumes:
      - ./grafana/grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    ports: 
      - "3000:3000"
    networks: 
      - monitoring
    restart: unless-stopped

  collector:
    build: ./collector
    container_name: collector
    stdin_open: true
    tty: true
    networks: 
      - monitoring
    depends_on:
      - grafana


networks: 
  monitoring:
    name: monitoring